README.md
pkg/apis/service/v1alpha2/servicebinding_lifecycle.go
samples/service-binding.yaml

Align with the spec RC2

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go

Add tests for binding .Do() and .Undo()

---

.github/workflows/ci.yaml
README.md
config/config-kapp.yaml
samples/spring-petclinic/service.yaml

Adding basic acceptance tests using the spring-petclinic sample.
Resolves #34 
Refs #11

Use kapp to install

---

.github/workflows/ci.yaml

Run acceptance for PRs

---

.github/workflows/ci.yaml

Run acceptance tests on k8s 1.19

---

.github/workflows/ci.yaml
go.mod

Use go 1.15

---

CODE_OF_CONDUCT.md

Adopt Contributor Covenant version 2.0

---

.github/workflows/ci.yaml

Test on k8s 1.20

---

.github/workflows/ci.yaml

Consume latest versions of kapp, kind and ko

---

.github/workflows/ci.yaml

Use vmware-tanzu/carvel-setup-action to install kapp

---

.github/workflows/ci.yaml

Bump kind@v0.11.1

---

.github/workflows/ci.yaml
config/carvel/bundle.yaml
config/carvel/package.yaml

Tanzu packaging with image pull secret.
Resolves #175

Tanzu packaging with image pull secret

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: daniel <dpfein@gmail.com>

Added templates for issues and PRs

---

.github/workflows/ci.yaml

Update CI local registry port settings.

Update imgpkg port settings

---

README.md
docs/troubleshooting.md

Pull request
Added documentation of troubleshooting 
Fixes #
N/A
Links follow through web browser

Added troubleshooting documentation

---

docs/troubleshooting.md

Pull request
Troubleshooting documentation has an error in the format
Fixes #
N/A
N/A
N/A

Fixed troubleshooting documentation format

---

.github/workflows/ci.yaml

Add grype scan

---

README.md
docs/troubleshooting.md

Pull request
Updates troubleshooting documentation
Fixes #
N/A
N/A
N/A

Fixed troubleshooting documentation

---

go.sum

Pull request
cve-fix gopkg.in/yaml.v3
Fixes #

chore: cve-fix gopkg.in/yaml.v3

---

.github/workflows/ci.yaml

Pull request
Updated test k8s-matrix
Updated k8s version (and new)
- 1.18.20
- 1.19.16
- 1.20.15
- 1.21.12
- 1.22.9
- 1.23.6
Fixes #

Updated test k8s-matrix

---

.github/workflows/ci.yaml
go.mod
go.sum

Pull request
Upgrade GO version to 1.18
Fixes #
All unit test passed

Upgrade GO version to 1.18

---

.ko.yaml

Pull request
Updating base image to paketobuildpacks/run-jammy-tiny:latest. Buildpacks will be deprecating the Bionic stack and introducing the Jammy stack.
Fixes #

Updating base image to paketobuildpacks/run-jammy-tiny

---

.github/workflows/ci.yaml

Pull request
PR updates the CI matrix to include k8s version 1.25.2 for acceptance
Fixes #
Ran the CI successfully on the 1.25.2 version of k8s.

Updates matrix with  k8s version 1.25.2

---

.github/workflows/ci.yaml
.wokeignore
CONTRIBUTING.md

Signed-off-by: Ani Brahmamurthy <abrahmamurth@vmware.com>
Pull request
- Adding scan for inclusive terminology in CI. And Fail PRs that contains these scan errors
- Scan capability added to makefile `lint`
Fixes #

chore: add inclusive terminology scan and error fixes (test)

---

.ko.yaml

Pull request
This PR is to update the ko base image to v `0.1.42` of paketobuildpacks.
Fixes #

chore: Update ko base image

---

.github/workflows/ci.yaml

Pull request
Adding k8s version 1.26 as one of the versions tested in the CI pipeline for servicebinding 
Fixes #

chore: Add k8s version 1.26.0 to CI test pipeline

---

.github/workflows/ci.yaml

Pull request
This PR is to avoid rate limiting issue in CI acceptance tests by supply a valid github token
Fixes #

chore: add Github Token to CI step to avoid running into rate limiting

---

.ko.yaml

Pull request
This PR is to update ko base image to use `paketobuildpacks/run-jammy-tiny:0.1.44`
Fixes #

chore: Updated ko base image to run-jammy-tiny:0.1.44

---

.github/workflows/ci.yaml

Pull request
This PR is to utilize ghcr instead of docker.hub repository for release packaging servicebinding
Fixes #

chore: Moving to ghcr repository for packaging

---

.github/workflows/ci.yaml

Pull request
Fix CI scripts for multiple Kapp changes
Fixes #

build: Fix for multiple kapp changes

---

.github/workflows/ci.yaml

This reverts commit ff825fa6b57e19ca9d3a69a38eb19025c5980a61.
[CodeCov Git action](https://github.com/marketplace/actions/codecov) v4 is still in beta (`v4.0.0-beta.2`), Reverting bump until is released
Fixes N/A

Revert "chore: Bump codecov/codecov-action from 3 to 4 (#290)"

---

config/manager.yaml

Updates the securityContext in the container template of the deployment, to ensure it complies with the `restricted` Pod Security Standards and `enforce` Pod Security Admission
Fixes N/A

fix: Update securityContext config in deployment

---

.github/workflows/ci.yaml

Pull request
- vmware-tanzu/carvel-setup-action was moved to carvel-dev/setup-action
- Removed `imgpkg` fixed version from carvel-dev configuration to use the latest
Fixes N/A

chore: Update carvel-dev setup action

---

.github/workflows/ci.yaml

Pull request
Fixes the file copied in the ci
Fixes N/A

Fix openshift file configuration in ci
