vmware-tanzu/servicebinding

.github/workflows/ci.yaml
pkg/reconciler/provisionedservice/controller_test.go
pkg/reconciler/servicebinding/controller_test.go
pkg/reconciler/servicebindingprep/controller_test.go
pkg/reconciler/servicebindingprep/resources/secret_test.go
pkg/resolver/serviceable_resolver_test.go

Add stub tests to packages that should have tests, but don't so that
they are reported with 0% coverage.
Resolves #17

Report unit test coverage to codecov

---

README.md
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go
pkg/reconciler/servicebinding/resources/servicebindingprojection.go
pkg/reconciler/servicebinding/resources/servicebindingprojection_test.go
pkg/reconciler/servicebindingprojection/controller.go
pkg/reconciler/servicebindingprojection/servicebindingprojection.go
pkg/reconciler/servicebindingprojection/servicebindingprojection_test.go
pkg/reconciler/testing/listers.go
samples/custom-projection/README.md
samples/custom-projection/service-binding.yaml
samples/custom-projection/service.yaml

Implements https://github.com/k8s-service-bindings/spec/tree/1.0.0-rc2#custom-projection
Resources wishing to opt-out of the default projection must set the projection type annotation on the ServiceBinding to `Custom`:
```yaml
....
metadata:
...
annotations:
projection.service.binding/type: Custom
```
Our `ServiceBinding` implementation will always create the
`ServiceBindingProjection`, even for non-custom projections for our own
internal use. Now we no longer reconcile the projection if the custom
projection annotation is set on the binding.

Implement Custom Projections extension

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_types.go
pkg/reconciler/servicebinding/resources/names/secret.go
pkg/reconciler/servicebindingprojection/servicebindingprojection_test.go

Annotation and Volume names are limited to 63 characters. We must not
compose a name longer than that limit. Use a truncated sha1 as a stable
value that will not exceed the limit.
Resolves #13

Gracefully handle long service binding names

---

config/300-provisionedservice.yaml
config/300-servicebinding.yaml
config/300-servicebindingprojection.yaml
config/400-webhook-configuration.yaml
config/kapp/config-kapp.yaml

These api version are supported and the v1beta1 version is deprecated as
of k8s 1.16.

Use apiextensions.k8s.io/v1 and admissionregistration.k8s.io/v1

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go
samples/controlled-resource/README.md
samples/spring-petclinic/README.md

The spec used both names, normalizing to the singular.

SERVICE_BINDINGS_ROOT -> SERVICE_BINDING_ROOT

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go
samples/spring-petclinic/application.yaml

This reverts commit cf501e779e8543c3a20e7d16c410001d78636992.
Resolves #51

Revert "Preserve backwards compatibility, for now"

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go
pkg/reconciler/servicebindingprojection/servicebindingprojection_test.go

Better handle multiple ServiceBinding resources each targeting the same
application resource. Depending on the order ServiceBindings are applied
to the resource, the order of the resulting volumes, volume mounts and
environment variables could differ. This difference could create churn
on the API server for semantically equivalent resources. Now, we attempt
to sort the entries injected into these lists for the ServiceBindings.
Resolves #66

Multi-ServiceBindings for a single application

---

README.md
pkg/resolver/serviceable_resolver.go
pkg/resolver/serviceable_resolver_test.go
samples/controlled-resource/service-binding.yaml
samples/controlled-resource/service.yaml
samples/custom-projection/README.md
samples/custom-projection/application.yaml
samples/custom-projection/service-binding.yaml
samples/environment-variable-mappings/service-binding.yaml
samples/environment-variable-mappings/service.yaml
samples/provisioned-service/README.md
samples/provisioned-service/application.yaml
samples/provisioned-service/service-binding.yaml
samples/provisioned-service/service.yaml
samples/spring-petclinic/service-binding.yaml
samples/spring-petclinic/service.yaml

Tracking  https://github.com/k8s-service-bindings/spec/pull/104

Allow binding directly from secrets

---

pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_lifecycle.go
pkg/apis/servicebindinginternal/v1alpha2/servicebindingprojection_test.go

This provides robustness against a controller that attempts to remove
the `internal.service.binding/projection-*` annotation, as the mutating
webhook will detect the change and reapply the annotation.
By cleaning up based on both source values, we can be more certain that
conflicts can be avoided.
Resolves #67

Cleanup injected values based on annotations and ServiceBindingProjection

---

config/300-provisionedservice.yaml

Refs https://github.com/k8s-service-bindings/spec/issues/81

Add label to ProvisionedService CRD to aid discovery

---

.vscode/settings.json
cmd/labs-service-bindings-manager/main.go
config/100-namespace.yaml
config/manager.yaml

Workaround for an upstream knative issue that cause corruption within
the mutating webhook configuration for intercepting bound applications.
Refs #130

Add 'knative.dev' to include/exclude labels

---

.github/dependabot.yml

Non-patch Kubernetes releases need to be cordinated with the upstream
Knative libraries. We should ignore them to avoid accidental merges of
Dependabot PRs.

Ignore major (semver minor) k8s.io updates

---

.github/workflows/ci.yaml
config/carvel/package.yaml

The service-binding.yaml file is now moved under the config directory
within the bundle. This makes it easier to apply a directory of config
to a cluster.
Resolves #163

Move config under a directory in imgpkg bundle

---

pkg/apis/servicebinding/v1alpha3/servicebinding_lifecycle.go
pkg/apis/servicebinding/v1alpha3/servicebinding_test.go
pkg/reconciler/servicebinding/servicebinding.go
pkg/reconciler/servicebinding/servicebinding_test.go

Pull request
K8s API server is rejecting status condition with no values. So update initialize conditions func to initialize all fields in status resource.
Fixes #177 
Use the testcase from #177 issue.

Iniitialize status conditions

---

.github/workflows/ci.yaml

Pull request
Issue found with `imgpkg v0.23.0` 
This PR downgrades to `imgpkg` GHA plugin to `v0.22.0`. 
Fixes #197 
<detail>
copy | importing 2 images...
copy | done uploading images
imgpkg: Error: Updating Image Refs registry.local:5000/service-bindings/bundle@sha256:8db097671917f25f32d5a7afe54f95a0c112728e024c9f80524d45b11438ea82:
Fetching images of registry.local:5000/service-bindings/bundle@sha256:8db097671917f25f32d5a7afe54f95a0c112728e024c9f80524d45b11438ea82:
Fetching location image:
Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving; Get "http://registry.local:5000/v2/": dial tcp: lookup registry.local on 127.0.0.53:53: server misbehaving
Error: Process completed with exit …

downgrade imgpkg to v0.22.0

---

README.md

There are no significant spec changes required to support RC3 since our
last functionality update.

Bump spec support to 1.0 RC3

---

.github/workflows/ci.yaml
config/200-clusterrole.yaml
config/400-webhook-configuration.yaml
config/carvel/package-install.values.yaml
config/carvel/package-install.yaml
config/config-kapp.yaml

A kapp deploy will attempt to make the resources on the api server match
the resources defined locally. Because the manager will modify the
resources we create at runtime, we should respect those mutations and
avoid overwriting them. This is typically done with rebase rules in the
kapp config resource.
During the acceptance tests, we set the kapp-controller sync period for
the package to 1 minute. If we see multiple changeset, the config is not
stable.

Test for clean redeploys with kapp

---

.github/workflows/ci.yaml

This adds validation that Service Binding becomes Ready in CI. This was used as part of testing in #217 for the issue #214.

Add test to CI that verifies Binding readiness

---

.github/workflows/ci.yaml

- make sure ServiceBinding resource are listed and described
- use `kubectl wait` to check for status conditions

Polishing CI script

---

config/config-logging.yaml

Pull request
- Enabled `config-logging`
- Sets `"timeEncoder": "rfc3339nano"`
Fixes #223 
Log snippet after config update
```sh
{"level":"info","ts":"2022-03-02T18:19:36.1942387Z","logger":"webhook.ValidationWebhook","caller":"controller/controller.go:538","msg":"Reconcile succeeded","knative.dev/traceid":"a64b6f1e-d543-43bc-abcb-e5b5955b3f11","knative.dev/key":"validation.webhook.bindings.labs.vmware.com","duration":0.0106878}
{"level":"info","ts":"2022-03-02T18:19:36.1963836Z","logger":"webhook.DefaultingWebhook","caller":"controller/controller.go:538","msg":"Reconcile succeeded","knative.dev/traceid":"db874d27-8b62-472f-a7f6-41618e14099f","knative.dev/key":"defaulting.webhook.bindings.labs.vmware.com","duration":0.0122473} …
```

Updated log time stamp format to match RFC-3339

---

.ko.yaml
README.md
config/300-servicebinding.yaml
samples/controlled-resource/service-binding.yaml
samples/multi-binding/service-binding.yaml
samples/overridden-type-provider/service-binding.yaml
samples/provisioned-service/service-binding.yaml
samples/spring-petclinic/service-binding.yaml

The API is compatible with v1alpha3 and does not require a conversion
webhook. The controller and webhook still operate against v1alpha3, and
can be upgraded at some point in the future.

Support servicebinding.io/v1beta1

---

config/200-clusterrole.yaml

Pull request
- Added TAP aggregate roles
- Removed unused roles
Fixes #

Add TAP aggregate roles

---

pkg/resolver/serviceable_resolver.go

Pull request
Tactical fix for `Postgres` resource pluralization. Correcting this bug using DynamicRestMapper requires major refactoring. We will clean up this implementation as we refactor this operator.
Fixes #190 
Unit test for `pkg/resolver/serviceable_resolver_test.go` requires registering types. API group `sql.tanzu.vmware.com` is not public and did not register. Manual testing installing Tanzu Postgres Operator

Resource pluralization for Postgres

---

samples/spring-petclinic/workload.yaml

The petclinic image was hosted on my personal dockerhub account. While
it is a "public" image, Docker Hub has started to require auth to pull.
Switching to GitHub Container Registry so that it's a repository under
the control of this project, and actually public.

Switch petclinic image to ghcr

---

.github/workflows/ci.yaml
.ko.yaml

Pull request
ko base image is updated to `run-jammy-static:0.0.28` that decreases package footprint
Fixes #

chore: updated ko base image to run-jammy-static:0.0.28

---

.github/workflows/ci.yaml

Pull request
Update `.github/workflows/ci.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo ::set-output name=version::$(cat VERSION)
```
**TO-BE**
```yaml
echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
```
Fixes #286 
None
None

chore: Replace deprecated command with environment file

---

.github/workflows/ci.yaml
config/carvel/openshift.yaml
config/carvel/package-install.values.yaml
config/carvel/package-install.yaml
config/carvel/package.yaml

When adding the security context, the component fails to be installed in an openshift cluster due to it does not match any securitycontextconstraint
Fixes N/A
* Install TAP in a openshift cluster
* Apply the following file
<details><summary>Click to expand</summary>
```yaml
#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
​
#@ kubernetes_distribution = data.values.kubernetes_distribution
#@ validDistributions = [None, "", "openshift"]
#@ if kubernetes_distribution not in validDistributions:
#@   assert.fail("{} not in {}".format(kubernetes_distribution, validDistributions))
#@ end
​
#@ if kubernetes_distribution == "openshift":
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: service-binding-nonroot-scc
namespace: service-bindings
rules:
- apiGroups:
- …
```

fix: Add Security context constrint for openshift
